/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankyouRouteImport } from './routes/thankyou'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ScannerDemoRouteImport } from './routes/scanner-demo'
import { Route as CreateSessionRouteImport } from './routes/create-session'
import { Route as IndexRouteImport } from './routes/index'

const ThankyouRoute = ThankyouRouteImport.update({
  id: '/thankyou',
  path: '/thankyou',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerDemoRoute = ScannerDemoRouteImport.update({
  id: '/scanner-demo',
  path: '/scanner-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateSessionRoute = CreateSessionRouteImport.update({
  id: '/create-session',
  path: '/create-session',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-session': typeof CreateSessionRoute
  '/scanner-demo': typeof ScannerDemoRoute
  '/session': typeof SessionRoute
  '/thankyou': typeof ThankyouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-session': typeof CreateSessionRoute
  '/scanner-demo': typeof ScannerDemoRoute
  '/session': typeof SessionRoute
  '/thankyou': typeof ThankyouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-session': typeof CreateSessionRoute
  '/scanner-demo': typeof ScannerDemoRoute
  '/session': typeof SessionRoute
  '/thankyou': typeof ThankyouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-session'
    | '/scanner-demo'
    | '/session'
    | '/thankyou'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-session' | '/scanner-demo' | '/session' | '/thankyou'
  id:
    | '__root__'
    | '/'
    | '/create-session'
    | '/scanner-demo'
    | '/session'
    | '/thankyou'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateSessionRoute: typeof CreateSessionRoute
  ScannerDemoRoute: typeof ScannerDemoRoute
  SessionRoute: typeof SessionRoute
  ThankyouRoute: typeof ThankyouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thankyou': {
      id: '/thankyou'
      path: '/thankyou'
      fullPath: '/thankyou'
      preLoaderRoute: typeof ThankyouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner-demo': {
      id: '/scanner-demo'
      path: '/scanner-demo'
      fullPath: '/scanner-demo'
      preLoaderRoute: typeof ScannerDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-session': {
      id: '/create-session'
      path: '/create-session'
      fullPath: '/create-session'
      preLoaderRoute: typeof CreateSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateSessionRoute: CreateSessionRoute,
  ScannerDemoRoute: ScannerDemoRoute,
  SessionRoute: SessionRoute,
  ThankyouRoute: ThankyouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
