name: Feature request
description: Suggest an improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user problem should this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should change?
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Chrome extension
        - Mobile app
        - Web app
        - Scanner signaling API
        - Scanner protocol
        - Documentation
        - Unsure
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
