workspace("ios/Volt.xcworkspace")
scheme("VoltScreenshots")

output_directory("fastlane/screenshots")
clear_previous_screenshots(true)
stop_after_first_error(true)

devices([
  "iPhone 17 Pro Max"
])

languages([
  "en-US"
])

launch_arguments([
  "--ui-testing",
  "--screenshots"
])
